### ISSUE TITLE
Issue with method 'referentiel(self, referentiel)' in 'offres_emploi/api.py'

### ISSUE THREAD

**Issue by GuillaumeOndongh** [etiennekintzler/api-offres-emploi#1]
Hi, there is an issue when runing 'offres_emploi/api.py' method `referentiel(self, referentiel)`

--> 165         print('Making request with params {}'.format(params))

NameError: name 'params' is not defined

You could comment/remove/fix the line.

Regards

**Comment by etiennekintzler** [comment]
fixed in #2
